server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:db/changelog/log-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/logOfvehicle
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

